name = "trends"
main = "src/main.py"
compatibility_date = "2026-04-08"
compatibility_flags = ["python_workers"]
workers_dev = true

[assets]
directory = "./static"

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "trends"
database_id = "b9c7682d-27db-4424-a567-f6099504116e"
migrations_dir = "migrations"
