name = "trends"
main = "src/main.py"
compatibility_date = "2026-04-08"
compatibility_flags = ["python_workers"]
workers_dev = true

# Required for post APIs and homepage queries.
# Replace with your actual D1 database details.
# [[d1_databases]]
# binding = "DB"
# database_name = "trends"
# database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
# migrations_dir = "migrations"

[observability.logs]
enabled = true

[[d1_databases]]
binding = "trends"
database_name = "trends"
database_id = "b9c7682d-27db-4424-a567-f6099504116e"